#!/usr/bin/env bash
# bash script to install nginx web server & make the following configurations:
#   - Nginx should be listening on port 80
#   - Return page containing "Holberton School" when queried

apt-get update
apt-get install -y nginx

# Change default Nginx page content
echo "Holberton School for the win!" > /var/www/html/index.html

# Verify Nginx is listening on port 80
netstat -tulpen | grep nginx | grep -q ":80 "

# Restart Nginx service
/etc/init.d/nginx reload
